CREATE SEQUENCE school_seq START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE TABLE SCHOOL(
   ID BIGINT PRIMARY KEY,
   NAME VARCHAR(256) NOT NULL,
   DESCRIPTION VARCHAR (256) NOT NULL
);
COMMIT;

CREATE SEQUENCE school_class_seq START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE TABLE SCHOOL_CLASS(
   ID BIGINT PRIMARY KEY,
   NAME VARCHAR(256) NOT NULL,
   TOTAL_STUDENTS BIGINT NOT NULL,
   SCHOOL_ID BIGINT NOT NULL,
   FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL(ID)
);
COMMIT;